# Generated by Django 4.2 on 2023-04-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_problem_is_solved_problem_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problem_id',
        ),
    ]
