# Generated by Django 4.2 on 2023-04-30 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_problem_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='problems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Task', to='task.problem'),
        ),
    ]
