# Generated by Django 4.2 on 2023-04-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='problems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='task.problem'),
        ),
    ]
