# Generated by Django 4.2 on 2023-04-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_problems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='problems',
        ),
        migrations.AddField(
            model_name='task',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='task.problem'),
        ),
    ]
